/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { Reserva, Usuario, Obra, Empresa, ReservaStatus, SystemSettings } from '../types';
import { Utensils, Calendar, ShieldCheck, TrendingUp, TrendingDown, DollarSign, Award, Percent } from 'lucide-react';

interface DashboardViewProps {
  reservas: Reserva[];
  usuarios: Usuario[];
  obras: Obra[];
  empresas: Empresa[];
  settings: SystemSettings;
  todayDate: string;
}

export default function DashboardView({ reservas, usuarios, obras, empresas, settings, todayDate }: DashboardViewProps) {
  
  // Base Helpers
  const getUsuario = (id: string) => usuarios.find(u => u.id === id);
  const getEmpresa = (id: string) => empresas.find(e => e.id === id);
  
  // Format date display nicely (DD/MM/AAAA)
  const formatDateDisplay = (dateStr: string) => {
    const parts = dateStr.split('-');
    if (parts.length === 3) {
      return `${parts[2]}/${parts[1]}/${parts[0]}`;
    }
    return dateStr;
  };

  const getMonthName = (dateStr: string) => {
    const parts = dateStr.split('-');
    if (parts.length === 3) {
      const monthIndex = Number(parts[1]) - 1;
      const months = [
        'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
        'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'
      ];
      return `Mês de ${months[monthIndex]}`;
    }
    return 'Mês Atual';
  };

  const getWeekDates = (dateStr: string) => {
    const dates = [];
    const [year, month, day] = dateStr.split('-').map(Number);
    const baseDate = new Date(year, month - 1, day);
    
    // Find Monday of this week
    const dayOfWeek = baseDate.getDay(); // 0 Sunday, 1 Monday, etc
    const diffToMonday = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
    
    const monday = new Date(baseDate);
    monday.setDate(baseDate.getDate() + diffToMonday);
    
    for (let i = 0; i < 7; i++) {
      const d = new Date(monday);
      d.setDate(monday.getDate() + i);
      const y = d.getFullYear();
      const m = String(d.getMonth() + 1).padStart(2, '0');
      const dayVal = String(d.getDate()).padStart(2, '0');
      dates.push(`${y}-${m}-${dayVal}`);
    }
    return dates;
  };

  // Calculate price for a user, taking optional obraId into account
  const getMealPrice = (user?: Usuario, obraId?: string) => {
    const targetObraId = obraId || user?.idObraPadrao;
    const obra = targetObraId ? obras.find(o => o.id === targetObraId) : undefined;
    
    // Obra custom price or fallback to global settings
    if (obra && obra.valorRefeicao !== undefined && obra.valorRefeicao > 0) {
      return obra.valorRefeicao;
    }
    return settings.valorRefeicaoPropria;
  };

  // 1. Total meals booked for Today
  const hojeDate = todayDate;
  const reservasHoje = reservas.filter(r => r.data === hojeDate);
  const reservadoHojeCount = reservasHoje.filter(r => r.status === ReservaStatus.Reservado).length;
  
  // Se o tablet não estiver ativo, considera todas as reservas ativas como consumidas/entregues
  const consumidoHojeCount = reservasHoje.filter(
    r => r.status === ReservaStatus.Reservado && (r.consumido || !settings.usarTabletRetirada)
  ).length;

  // 2. Week total
  const weekDates = getWeekDates(hojeDate);
  const reservasSemana = reservas.filter(r => weekDates.includes(r.data));
  const reservadoSemanaCount = reservasSemana.filter(r => r.status === ReservaStatus.Reservado).length;

  // 3. Month total
  const currentMonthPrefix = hojeDate.substring(0, 7); // "YYYY-MM"
  const reservasMes = reservas.filter(r => r.data.startsWith(currentMonthPrefix));
  const reservadoMesCount = reservasMes.filter(r => r.status === ReservaStatus.Reservado).length;

  // 4. Cancellation Rate
  const totalReservationsMes = reservasMes.length; // Booked + Cancelled
  const cancelamentosMes = reservasMes.filter(r => r.status === ReservaStatus.Cancelado).length;
  const percentCancelamento = totalReservationsMes > 0 
    ? Math.round((cancelamentosMes / totalReservationsMes) * 100)
    : 0;

  // 5. Economy generated by timely cancellations (before 08:30)
  let economiaTotal = 0;
  reservasMes.forEach(r => {
    if (r.status === ReservaStatus.Cancelado) {
      const user = getUsuario(r.idUsuario);
      economiaTotal += getMealPrice(user, r.idObraNoDia);
    }
  });

  // 6. Food Waste (Reserved but NOT consumed up to Today)
  const pastDates = weekDates.filter(d => d < hojeDate);
  const reservasPassadas = reservas.filter(r => pastDates.includes(r.data));
  
  // Se o refeitório não exige verificação no tablet, não há "desperdício auditado por falta", assume-se entregue/consumido
  const desperdicioCount = settings.usarTabletRetirada 
    ? reservasPassadas.filter(r => r.status === ReservaStatus.Reservado && !r.consumido).length
    : 0;
    
  let desperdicioCusto = 0;
  if (settings.usarTabletRetirada) {
    reservasPassadas.forEach(r => {
      if (r.status === ReservaStatus.Reservado && !r.consumido) {
        const user = getUsuario(r.idUsuario);
        desperdicioCusto += getMealPrice(user, r.idObraNoDia);
      }
    });
  }

  // 7. Top 10 Obras with Highest Consumption
  const obraStats: Record<string, number> = {};
  obras.forEach(o => { obraStats[o.id] = 0; });
  
  reservas.forEach(r => {
    if (r.status === ReservaStatus.Reservado) {
      // Find where reservation occurred or user standard
      const user = getUsuario(r.idUsuario);
      const obraId = r.idObraNoDia || (user ? user.idObraPadrao : null);
      if (obraId) {
        obraStats[obraId] = (obraStats[obraId] || 0) + 1;
      }
    }
  });

  const sortedObras = Object.entries(obraStats)
    .map(([id, sum]) => {
      const o = obras.find(item => item.id === id);
      return {
        id,
        nome: o ? o.nome : 'Outra / Desconhecida',
        cc: o ? o.centroCusto : 'CC SGR',
        total: sum
      };
    })
    .sort((a, b) => b.total - a.total);

  return (
    <div className="space-y-6" id="dashboard-view-panel">
      {/* Overview Title */}
      <div>
        <h2 className="text-xl font-bold text-neutral-800 tracking-tight flex items-center gap-2">
          <TrendingUp className="h-5 w-5 text-emerald-600" /> Indicadores de Controle de Refeições
        </h2>
        <p className="text-xs text-neutral-600">
          Dados métricos em tempo real calculados sobre reservas, cancelamentos estruturados e faturas.
        </p>
      </div>

      {/* Grid Indicators */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {/* Card 1: Hoje */}
        <div className="bg-white p-4 rounded-xl border border-neutral-200 shadow-sm flex flex-col justify-between" id="metric-card-hoje">
          <div className="flex justify-between items-start">
            <div>
              <span className="block text-[11px] font-mono text-neutral-500 uppercase font-bold">Hoje ({formatDateDisplay(hojeDate)})</span>
              <span className="text-2xl font-extrabold text-neutral-900 mt-1 block">
                {reservadoHojeCount} <span className="text-sm font-normal text-neutral-500">Reservadas</span>
              </span>
            </div>
            <div className="p-2 bg-emerald-50 text-emerald-600 rounded-lg">
              <Utensils className="h-5 w-5" />
            </div>
          </div>
          <div className="mt-3 pt-3 border-t border-neutral-100 flex justify-between items-center text-xs">
            <span className="text-neutral-500">
              {settings.usarTabletRetirada ? 'Após Leitura Facial (Tablet):' : 'Confirmado (Lista Física):'}
            </span>
            <span className="font-semibold text-emerald-600 font-mono">{consumidoHojeCount} de {reservadoHojeCount}</span>
          </div>
        </div>

        {/* Card 2: Semana e Mês */}
        <div className="bg-white p-4 rounded-xl border border-neutral-200 shadow-sm flex flex-col justify-between" id="metric-card-period">
          <div className="flex justify-between items-start">
            <div>
              <span className="block text-[11px] font-mono text-neutral-500 uppercase font-bold">{getMonthName(hojeDate)}</span>
              <span className="text-2xl font-extrabold text-neutral-900 mt-1 block">
                {reservadoMesCount} <span className="text-sm font-normal text-neutral-500">Reservadas</span>
              </span>
            </div>
            <div className="p-2 bg-sky-50 text-sky-600 rounded-lg">
              <Calendar className="h-5 w-5" />
            </div>
          </div>
          <div className="mt-3 pt-3 border-t border-neutral-100 flex justify-between items-center text-xs">
            <span className="text-neutral-500">Na semana corrente:</span>
            <span className="font-semibold text-neutral-800 font-mono">{reservadoSemanaCount} total</span>
          </div>
        </div>

        {/* Card 3: Economia gerada */}
        <div className="bg-white p-4 rounded-xl border border-emerald-100 shadow-sm flex flex-col justify-between bg-emerald-50/10" id="metric-card-economia">
          <div className="flex justify-between items-start">
            <div>
              <span className="block text-[11px] font-mono text-emerald-600 uppercase font-bold">Economia Gerada</span>
              <span className="text-2xl font-extrabold text-emerald-700 mt-1 block">
                R$ {economiaTotal.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </span>
            </div>
            <div className="p-2 bg-emerald-100 text-emerald-700 rounded-lg">
              <DollarSign className="h-5 w-5" />
            </div>
          </div>
          <div className="mt-3 pt-3 border-t border-emerald-100 flex justify-between items-center text-xs">
            <span className="text-emerald-600 font-medium">Cancelados no prazo (&lt;{settings.horarioLimite}):</span>
            <span className="font-bold text-emerald-700 font-mono">{cancelamentosMes} refeições</span>
          </div>
        </div>
      </div>

      {/* Top Obras and Cost Breakdown Details split */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Top Obras chart */}
        <div className="bg-white p-5 rounded-xl border border-neutral-200 shadow-sm lg:col-span-2 flex flex-col" id="dashboard-obras-panel">
          <h3 className="font-bold text-neutral-800 text-sm mb-4 uppercase tracking-wider text-xs flex items-center gap-2">
            <Award className="h-4 w-4 text-amber-500" /> Ranking: Consumo por Obra (Reservas Confirmadas)
          </h3>
          
          <div className="space-y-4 flex-1">
            {sortedObras.length === 0 ? (
              <p className="text-xs text-neutral-500 py-6 text-center">Nenhuma reserva cadastrada para as obras ainda.</p>
            ) : (
              sortedObras.map((o, idx) => {
                const maxVal = sortedObras[0]?.total || 1;
                const percentage = Math.round((o.total / maxVal) * 100);

                return (
                  <div key={o.id} className="space-y-1">
                    <div className="flex justify-between text-xs">
                      <div>
                        <span className="font-mono text-neutral-400 mr-2 font-bold">{idx + 1}.</span>
                        <span className="font-semibold text-neutral-700">{o.nome}</span>
                        <span className="text-neutral-400 text-[10px] ml-2 font-mono">({o.cc})</span>
                      </div>
                      <span className="font-bold text-neutral-800 font-mono">{o.total} refeições</span>
                    </div>
                    {/* Linear gauge bar */}
                    <div className="w-full h-2 bg-neutral-100 rounded-full overflow-hidden">
                      <div 
                        className={`h-full rounded-full transition-all duration-500 ${
                          idx === 0 
                            ? 'bg-emerald-500' 
                            : idx === 1 
                            ? 'bg-emerald-400' 
                            : idx === 2 
                            ? 'bg-emerald-300' 
                            : 'bg-neutral-400'
                        }`}
                        style={{ width: `${percentage}%` }}
                      />
                    </div>
                  </div>
                );
              })
            )}
          </div>
          
          <div className="mt-4 pt-4 border-t border-neutral-100 text-[11px] text-neutral-500 bg-neutral-50 p-2.5 rounded">
            📌 **Fórmula de Desperdício:** Calculamos a "Falta de Retirada" comparando as reservas ativas de dias passados que não receberam a confirmação de leitura facial na cozinha. Esse controle economiza milhares de reais às construtoras!
          </div>
        </div>

        {/* Integration Callout */}
        <div className="bg-gradient-to-br from-neutral-900 to-neutral-950 text-white p-5 rounded-xl border border-neutral-800 shadow-lg flex flex-col justify-between" id="integration-teaser-panel">
          <div>
            <h4 className="font-bold font-mono text-[10px] text-emerald-400 tracking-wider uppercase mb-2">
              SGE INTEGRADO & FACIAL
            </h4>
            <h3 className="text-base font-bold text-white mb-2 leading-tight">
              Reconhecimento Facial & ERP Sienge
            </h3>
            <p className="text-xs text-neutral-400 leading-relaxed mb-4">
              O sistema possui arquitetura nativa com endpoints de leitura de catracas faciais na portaria ou refeitório, gravando carimbos e vinculando centros de custos por empreiteiras em tempo real.
            </p>

            <ul className="space-y-2 text-xs text-neutral-300">
              <li className="flex items-start gap-2">
                <span className="text-emerald-400 mt-0.5">✔</span>
                <span>Prevenção contra falsidade de marcas</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-emerald-400 mt-0.5">✔</span>
                <span>Distribuição automática de custos em ERP</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-emerald-400 mt-0.5">✔</span>
                <span>Sincronização cadastral via lote JSON</span>
              </li>
            </ul>
          </div>

          <div className="mt-5 pt-4 border-t border-neutral-800 text-[10px] text-neutral-500 flex gap-2">
            <span>Serviço: Ativo</span>
            <span>•</span>
            <span>API Sienge: Configurada</span>
          </div>
        </div>

      </div>
    </div>
  );
}
