import type { VercelRequest, VercelResponse } from '@vercel/node';
import { initializeApp, getApps, cert, App } from 'firebase-admin/app';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';
import { getMessaging } from 'firebase-admin/messaging';
import firebaseConfig from '../firebase-applet-config.json' with { type: 'json' };

// Initialize Firebase Admin SDK using modern modular APIs
let app: App;
const existingApps = getApps();

if (existingApps.length === 0) {
  const serviceAccountEnv = process.env.FIREBASE_SERVICE_ACCOUNT;
    const privateKey = process.env.FIREBASE_PRIVATE_KEY;
      const clientEmail = process.env.FIREBASE_CLIENT_EMAIL;

        if (serviceAccountEnv) {
            try {
                  const serviceAccount = JSON.parse(serviceAccountEnv);
                        app = initializeApp({
                                credential: cert(serviceAccount)
                                      });
                                          } catch (e) {
                                                console.error('[Admin] Error parsing FIREBASE_SERVICE_ACCOUNT env var:', e);
                                                      app = initializeApp({
                                                              projectId: firebaseConfig.projectId
                                                                    });
                                                                        }
                                                                          } else if (privateKey && clientEmail) {
                                                                              app = initializeApp({
                                                                                    credential: cert({
                                                                                            projectId: firebaseConfig.projectId,
                                                                                                    clientEmail: clientEmail,
                                                                                                            privateKey: privateKey.replace(/\\n/g, '\n'),
                                                                                                                  })
                                                                                                                      });
                                                                                                                        } else {
                                                                                                                            // Fallback to default environment credentials with configured project
                                                                                                                                app = initializeApp({
                                                                                                                                      projectId: firebaseConfig.projectId
                                                                                                                                          });
                                                                                                                                            }
                                                                                                                                            } else {
                                                                                                                                              app = existingApps[0];
                                                                                                                                              }

                                                                                                                                              // Instantiate Firestore targeting our specific database instance
                                                                                                                                              const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);
                                                                                                                                              const messaging = getMessaging(app);

                                                                                                                                              export default async function handler(req: VercelRequest, res: VercelResponse) {
                                                                                                                                                // Allow only POST or GET requests depending on invocation
                                                                                                                                                  const method = req.method;
                                                                                                                                                    if (method !== 'POST' && method !== 'GET') {
                                                                                                                                                        return res.status(405).json({ error: 'Method Not Allowed' });
                                                                                                                                                          }

                                                                                                                                                            try {
                                                                                                                                                                console.log('[FCM Daemon] Processing notification queue...');

                                                                                                                                                                    // 1. Fetch up to 400 unsent notifications from the queue
                                                                                                                                                                        const queueSnapshot = await db.collection('notificationQueue')
                                                                                                                                                                              .where('sent', '==', false)
                                                                                                                                                                                    .limit(400)
                                                                                                                                                                                          .get();

                                                                                                                                                                                              if (queueSnapshot.empty) {
                                                                                                                                                                                                    return res.status(200).json({
                                                                                                                                                                                                            success: true,
                                                                                                                                                                                                                    message: 'No pending notifications to send.'
                                                                                                                                                                                                                          });
                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                  // 2. Fetch all registered FCM tokens to map userId -> token
                                                                                                                                                                                                                                      const fcmSnapshot = await db.collection('fcmTokens').get();
                                                                                                                                                                                                                                          const userTokens: Record<string, string> = {};
                                                                                                                                                                                                                                              fcmSnapshot.forEach((doc) => {
                                                                                                                                                                                                                                                    const data = doc.data();
                                                                                                                                                                                                                                                          if (data.token && data.userId) {
                                                                                                                                                                                                                                                                  userTokens[data.userId] = data.token;
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                const results = { sent: 0, skipped: 0, errors: 0 };
                                                                                                                                                                                                                                                                                    const batch = db.batch();

                                                                                                                                                                                                                                                                                        // 3. Process each notification in the queue
                                                                                                                                                                                                                                                                                            for (const doc of queueSnapshot.docs) {
                                                                                                                                                                                                                                                                                                  const notification = doc.data();
                                                                                                                                                                                                                                                                                                        const token = userTokens[notification.userId];

                                                                                                                                                                                                                                                                                                              if (!token) {
                                                                                                                                                                                                                                                                                                                      console.warn(`[FCM] No token found for userId: ${notification.userId}. Skipping.`);
                                                                                                                                                                                                                                                                                                                              batch.update(doc.ref, {
                                                                                                                                                                                                                                                                                                                                        sent: true,
                                                                                                                                                                                                                                                                                                                                                  skippedAt: FieldValue.serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                            skipReason: 'no_token'
                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                            results.skipped++;
                                                                                                                                                                                                                                                                                                                                                                                    continue;
                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                        await messaging.send({
                                                                                                                                                                                                                                                                                                                                                                                                                  token,
                                                                                                                                                                                                                                                                                                                                                                                                                            notification: {
                                                                                                                                                                                                                                                                                                                                                                                                                                        title: notification.title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    body: notification.body,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        webpush: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    notification: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  icon: '/icon.png',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                badge: '/icon-badge.svg',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fcmOptions: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      link: notification.link || '/',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            batch.update(doc.ref, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sent: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sentAt: FieldValue.serverTimestamp()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                results.sent++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (sendError: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error(`[FCM] Error sending to token ${token}:`, sendError.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      batch.update(doc.ref, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sent: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          errorAt: FieldValue.serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    errorMessage: sendError.message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    results.errors++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await batch.commit();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`[FCM Daemon] Done. Sent: ${results.sent}, Skipped: ${results.skipped}, Errors: ${results.errors}`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return res.status(200).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ...results
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('[FCM Daemon] Fatal error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.status(500).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          error: 'Internal Server Error',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                message: error.message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
